### ISSUE TITLE
Port to 1.18.2

### ISSUE THREAD

**Issue by Morasiu** [Floweynt/tfc-support-indicator#2]
I need that for TerraFirmaCraft Hardrock modpack. Collapsing are so hard to understand!

**Comment by Morasiu** [comment]
Also I can sponsor you if you have BuyMeACoffee or Github Sponsors

**Comment by Floweynt** [comment]
[Done](https://modrinth.com/mod/tfc-support-indicator/version/1.0.2+mc1.18.2).

I don't have any sponsor things set up. Perhaps now would be good time to do so :smile:

**Comment by Morasiu** [comment]
My hero. Anyway. Good job!
